### ISSUE TITLE
JWT authorisation for signal API

### ISSUE THREAD

**Issue by holema** [jitsi/jitsi-component-selector#24]
Hello @emrahcom,

I just checked out your latest #22 and saw that you secured the API with a JWT.
In the Example https://github.com/nordeck/bullseye-lxc-jitsi/blob/9c4701721edf2dc20f37aaaced8ff7cfef0e5b5a/docs/component-selector-api-examples/sip-custom-1-start.sh#L62 I saw that you are using the kid: jitsi/signal. Is it important that the kid property is set?  I couldn't find any place in the source code where the property is parsed.

**Comment by emrahcom** [comment]
Hi @holema,

`jitsi-component-selector` doesn't use a shared secret for tokens, it uses public/private key pair. `Kid` is used to find the public key. Releated config is [here](https://github.com/jitsi/jitsi-component-selector/blob/main/env.example#L91-L93)

Let's say you used `jitsi/signal` as `kid` in your token, in this case `jitsi-component-selector` will get the public key from `https://localhost:18443/signal/d1c8dfc1830cc0985d98acb9c6606ccb191ffdeb5c2be295c446dcea80391620.pem`

`d1c8dfc1830cc0985d98acb9c6606ccb191ffdeb5c2be295c446dcea80391620` is the hash generated by using `kid`

```
echo -n 'jitsi/signal' | sha256sum
>>> d1c8dfc1830cc0985d98acb9c6606ccb191ffdeb5c2be295c446dcea80391620
```

**Comment by holema** [comment]
Thanks @emrahcom
